version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/app"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "npm"
    labels:
      - "npm dependencies"
